In [2]:
import pandas as pd
import numpy as np
import joblib

data = pd.read_csv("heart.csv")
print("Data loaded:", data.shape)


Data loaded: (1025, 14)


In [3]:
X = data.drop("target", axis=1)
y = data["target"]

print(X.shape, y.shape)


(1025, 13) (1025,)


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape, X_test.shape)


(820, 13) (205, 13)


In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("RF Accuracy:", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))


RF Accuracy: 0.9853658536585366
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.97      0.99       103

    accuracy                           0.99       205
   macro avg       0.99      0.99      0.99       205
weighted avg       0.99      0.99      0.99       205

[[102   0]
 [  3 100]]


In [7]:
import joblib

joblib.dump(rf, "heart_disease_rf.pkl")
print("Random Forest model saved")


Random Forest model saved


In [6]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Model trained successfully")


Model trained successfully


In [8]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="rbf", probability=True))
])

svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

print("SVM Accuracy:", accuracy_score(y_test, svm_pred))
print(classification_report(y_test, svm_pred))
print(confusion_matrix(y_test, svm_pred))


SVM Accuracy: 0.8878048780487805
              precision    recall  f1-score   support

           0       0.93      0.83      0.88       102
           1       0.85      0.94      0.89       103

    accuracy                           0.89       205
   macro avg       0.89      0.89      0.89       205
weighted avg       0.89      0.89      0.89       205

[[85 17]
 [ 6 97]]


In [9]:
joblib.dump(svm_model, "heart_disease_svm.pkl")
print("SVM model saved")


SVM model saved


In [9]:
y_pred = model.predict(X_test)
print("Prediction done")


Prediction done


In [10]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.7951219512195122
              precision    recall  f1-score   support

           0       0.85      0.72      0.78       102
           1       0.76      0.87      0.81       103

    accuracy                           0.80       205
   macro avg       0.80      0.79      0.79       205
weighted avg       0.80      0.80      0.79       205

[[73 29]
 [13 90]]


In [11]:
import joblib

joblib.dump(model, "heart_disease_model.pkl")
print("Model saved successfully")


Model saved successfully


In [12]:
import joblib
loaded_model = joblib.load("heart_disease_model.pkl")
print(type(loaded_model))


<class 'sklearn.linear_model._logistic.LogisticRegression'>


In [13]:
import numpy as np

sample = np.array([[52,1,0,125,212,0,1,168,0,1.0,2,2,3]])  # 13 features
pred = loaded_model.predict(sample)
print("Prediction:", pred)  # 0 = No, 1 = Yes


Prediction: [0]


C:\Users\Shivang Mishra\Downloads\New folder\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [14]:
import pandas as pd

sample_df = pd.DataFrame([[
    52,1,0,125,212,0,1,168,0,1.0,2,2,3
]], columns=X.columns)

pred = loaded_model.predict(sample_df)
print("Prediction:", pred)


Prediction: [0]
